/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SD_Clock.h"
#include "SPIM_SD.h"
#include "SPIM_SD_PVT.h"
#include "SD_SCLK_aliases.h"
#include "SD_SCLK.h"
#include "SD_MOSI_aliases.h"
#include "SD_MOSI.h"
#include "SD_MISO_aliases.h"
#include "SD_MISO.h"
#include "SD_CS_aliases.h"
#include "SD_CS.h"
#include "LED_0_aliases.h"
#include "LED_0.h"
#include "LED_1_aliases.h"
#include "LED_1.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

